[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python3"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd Flirt && npm install"]

[start]
cmd = "npm run deploy && cd Flirt && npm start"
